haproxy:
  container_name: iwhitelb 
  build: haproxy 
  ports:
    - "80:80"
    - "443:443"
    - "1936:1936"
viking:
  container_name: viking
  build: . 
  environment:
   - APP_ENV=local
   - APP_URL=http://api.local.viking.com
   - DB_DATABASE=mysql
  volumes:
   - .:/var/www/html
  ports:
   - "8001:81"
   - "8002:443"
 
