shieldmaiden:
  container_name: shieldmaiden
  build: . 
  environment:
   - APP_ENV=local
   - APP_URL=http://shieldmaiden.local.norse.com
   - DB_HOST=iceland
   - DB_DATABASE=discovercsv
   - DB_CONNECTION=mysql
   - DB_USERNAME=iwhite
   - DB_PASSWORD=iwhite5
  external_links:
   - iceland
   - langskip
  volumes:
   - .:/var/www/php
